# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-10 08:32
from __future__ import unicode_literals

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apost',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.get_image_path),
        ),
    ]
