# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-19 05:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180219_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDesc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=4000)),
                ('duration', models.CharField(max_length=255)),
                ('days_per_week', models.CharField(max_length=255)),
                ('hours_per_day', models.CharField(max_length=255)),
                ('fee', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='description', to='main.Course')),
            ],
        ),
        migrations.RemoveField(
            model_name='coursedescription',
            name='course_name',
        ),
        migrations.DeleteModel(
            name='CourseDescription',
        ),
    ]
